os: linux
dist: trusty
language: generic
sudo: required
services: docker
script:
  - while sleep 1m; do echo "=====[ still running ]====="; done &
  - make docker-build TRAVIS_DEPLOY=true
  - kill %1
